image: docs/images/PropWare_Logo_64.png
type: tools|libraries
links:
  Documentation: http://david.zemon.name/PropWare/
  Forum Thread: http://forums.parallax.com/showthread.php/157005-FYI-PropWare-Complete-build-system-and-library-for-PropGCC
  Issue Tracker: https://github.com/parallaxinc/PropWare/issues
  Source Code: https://github.com/parallaxinc/PropWare
  Build Server: https://ci.zemon.name/project.html?projectId=PropWare&tab=projectOverview&guest=1
